repos:
  # Basic utility hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files

  # isort for import order formatting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # Black for Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  # pylint for Python linting, adjusted to use Poetry
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args: ["--errors-only"]

  # Poetry checks
  - repo: local
    hooks:
      - id: poetry-check
        name: poetry-check
        entry: poetry check --lock
        language: system
        pass_filenames: false
        always_run: true

  # Codespell for spelling corrections
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args: ["--ignore-words-list", "ba,nd,Pyhton"]
        exclude: "poetry.lock"
