[tool.poetry]
name = "src"
version = "0.1.0"
description = "Experiments with Pycardano lib."
authors = ["Deep Bhatt <deep.bhatt@charli3.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pycardano = "^0.9.0"
retry = "^0.9.2"
pyyaml = "^6.0"
click = "^8.1.3"

[tool.poetry.group.dev.dependencies]
pylint = "^2.17.4"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
