local_script: false
mnemonic: test test test test test test test test test test test test test test test
  test test test test test test test test sauce
multisig_oracle_script_address: addr_test1wruvcdqgenkl6lsrqthwm5ez2ecvz24az6upwxqvf2hda7sgxf7dg
nodes_values:
- 41150
- 41150
oracle_info:
  multisig_oracle_script_address: addr_test1wr97wuv7862yj5ckaks6cqc8yau03gxn9rpfsm0790yscqscpluhs
  oracle_script_address: addr_test1wr97wuv7862yj5ckaks6cqc8yau03gxn9rpfsm0790yscqscpluhs
oracle_owner:
  script_start_slot: 1
  tC3_add_funds: 1000000000
  tC3_initial_amount: 300000
oracle_script_address: addr_test1wq4zmn7d93dw0wsz05nmdcdkn3mjff98flxhzqne33896xq2464cv
oracle_settings:
  os_aggregate_change: 200
  os_aggregate_time: 300000
  os_aggregate_valid_range: 300000
  os_divergence: 1500
  os_iqr_multiplier: 2
  os_minimum_deposit: 10000
  os_node_fee_price:
    aggregate_fee: 20
    node_fee: 10
    platform_fee: 10
  os_platform:
    pmultisig_threshold: 1
  os_updated_node_time: 300000
  os_updated_nodes: 10000
updated_oracle_settings:
  os_aggregate_change: 500
  os_aggregate_time: 2400000
  os_aggregate_valid_range: 300000
  os_divergence: 2500
  os_iqr_multiplier: 4
  os_minimum_deposit: 100000
  os_node_fee_price:
    aggregate_fee: 15
    node_fee: 12
    platform_fee: 9
  os_platform:
    pmultisig_threshold: 1
  os_updated_node_time: 2400000
  os_updated_nodes: 7000
