oracle_owner:
  script_start_slot: 1
  tC3_initial_amount: 1000
  tC3_add_funds: 2000


oracle_settings:
  os_updated_nodes: 6000
  os_updated_node_time: 1800000
  os_aggregate_time: 1800000
  os_aggregate_change: 200
  os_node_fee_price:
    node_fee: 10
    aggregate_fee: 20
    platform_fee: 10
  os_mad_multiplier: 20000
  os_divergence: 1500

updated_oracle_settings:
  os_updated_nodes: 7000
  os_updated_node_time: 2400000
  os_aggregate_time: 2400000
  os_aggregate_change: 500
  os_node_fee_price:
    node_fee: 12
    aggregate_fee: 15
    platform_fee: 9
  os_mad_multiplier: 5
  os_divergence: 3500
